### ISSUE TITLE
Issue with seasons

### ISSUE THREAD

**Issue by JamieBG** [niklongstone/amazon-date-parser#5]
Hi i'm having some issues with seasons...passing **2019-su** or **2019-wi** into AmazonDateParser gives me....

`2019-04-12T12:59:22.094Z	8723fdad-4204-4fde-8f3b-21eeb0064c06	Unexpected exception 'Error: Invalid constructor parameter or parameter not supported.':
Error: Invalid constructor parameter or parameter not supported.
at new AmazonDateParser (/var/task/node_modules/amazon-date-parser/index.js:88:23)
at searchDatabase (/var/task/index.js:629:19)
at Object.findExperienceIntentHandler (/var/task/index.js:370:23)
at Object.FindExperienceIntent (/var/task/index.js:63:31)
at emitNone (events.js:106:13)
at AlexaRequestEmitter.emit (events.js:208:7)
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:216:10)
at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:181:23)
at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:126:25)
at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:100:31)`

UPDATE, i also have the same issue with **2019-w16**

**Comment by niklongstone** [comment]
Sorry for the late reply.
It's a very simple issue, the parser is expecting an uppercase value.

you can try something like that:
```
var myDate = '2019-su';
var date = new AmazonDateParser(myDate.toUpperCase());
```

**Comment by JamieBG** [comment]
Hi thanks for replying. Yep, that’s exactly what I did!

Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
